# Generated by Django 6.0.7 on 2026-08-04 15:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[accounts.models.validate_full_name])),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[accounts.models.validate_gmail])),
                ('mobile', models.CharField(max_length=10, unique=True, validators=[accounts.models.validate_mobile])),
                ('password', models.CharField(max_length=255, validators=[accounts.models.validate_password])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
